In [2]:
import pandas as pd

In [1]:
import os

print(os.getcwd())

c:\Users\acer\OneDrive\Desktop\EchoChain-Lifecycle-Analytics\notebooks

In [8]:
olx = pd.read_excel("../data/raw/olx_dataset.xlsx")

ebay = pd.read_csv(
    "../data/raw/ebay_products.csv",
    engine="python",
    on_bad_lines="skip"
)

used = pd.read_csv("../data/raw/used_devices.csv")

print("OLX:", olx.shape)
print("eBay:", ebay.shape)
print("Used:", used.shape)

OLX: (3931, 11)
eBay: (17577, 30)
Used: (3454, 15)

In [9]:
print("OLX")
display(olx.head())
print(" eBay ")
display(ebay.head())
print("Used Devices ")
display(used.head())

OLX

,Unnamed: 0,categoryName,userName,dateJoined,location,price,title,brand,condition,description,adId
0,0,Mobiles,Straight Way,Member since Dec 2015,Pakistan,"Rs 115,000",iPhone 14 JV,Apple iPhone,New,Just Active \nBox pack \nnon used \nStorage : ...,Ad id 1090054705
1,1,Mobiles,Ali butt,Member since Dec 2020,Pakistan,"Rs 9,999",OPPO A57 4+64 for sale with complete box . 033...,OPPO,New,"condition NEW\ndual SIM with fingerprint,dual ...",Ad id 1084447867
2,2,Mobiles,Exit - Mobile Home,Member since Jan 2021,Pakistan,"Rs 122,000",Google Pixel 7 & 7A,Google,New,Google Pixel 7A\n* Storage: 128GB\n* RAM: 8GB\...,Ad id 1088157589
3,3,Mobiles,Ibraheem,Member since Sept 2022,Pakistan,"Rs 215,000",Samsung Galaxy S24 Ultra ...,Apple iPhone,New,Aslamualikum \n10/10 Brand New Condition\nComp...,Ad id 1089559092
4,4,Mobiles,Nouman Ch,Member since Dec 2018,Pakistan,"Rs 18,499",Samsung Tab A7 lite 3/32 LTE Data Sim Fresh Ge...,Samsung,New,Challenging Price in Market\nSamsung A7 lite W...,Ad id 1090008449

 eBay

,Uniq Id,Crawl Timestamp,Pageurl,Website,Title,Num Of Reviews,Average Rating,Number Of Ratings,Model Num,Sku,...,Specifications,Five Star,Four Star,Three Star,Two Star,One Star,Discontinued,Broken Link,Seller Rating,Seller Num Of Reviews
0,38c0bcb6ce1e5d1750b442dd9446aac9,2021-01-03 08:05:50 +0000,https://www.ebay.com/p/7024512090?iid=16461748...,ebay.com,Samsung Galaxy Note 8 6GB RAM 64GB Dual SIM (U...,NaN,NaN,NaN,SM-N950F,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN
1,31be03c526b3b65322e73ce617fa0e57,2021-02-17 06:24:23 +0000,https://www.ebay.com/itm/Apple-Airpods-Pro-wit...,ebay.com,Apple Airpods Pro with wireless charging case ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,False,100%,59
2,5f2eacffc44070e54ef3195d4e3889d1,2021-02-17 06:17:19 +0000,https://www.ebay.com/p/238211749?iid=174232921...,ebay.com,"Apple iPad Pro 1st Gen. 64GB, Wi-Fi + 4G (Unlo...",NaN,NaN,NaN,A1709,NaN,...,NaN,7.0,0.0,0.0,0.0,0.0,False,False,NaN,NaN
3,63769e57a0c804cd2871d813a835ed2b,2021-01-11 00:03:01 +0000,https://www.ebay.com/itm/Nintendo-wii-console-...,ebay.com,Nintendo wii console fit board and games bundle,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,False,100%,613
4,dd01861b46b2d5f2d24a64c1f64c5564,2021-02-10 15:03:24 +0000,https://www.ebay.com/itm/Fossil-smart-watch/16...,ebay.com,Fossil smart watch,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,False,100%,2

Used Devices

,brand_name,os,screen_size,4g,5g,main_camera_mp,selfie_camera_mp,int_memory,ram,battery,weight,release_year,days_used,normalized_used_price,normalized_new_price
0,Honor,Android,14.50,yes,no,13.0,5.0,64.0,3.0,3020.0,146.0,2020,127,4.307572,4.715100
1,Honor,Android,17.30,yes,yes,13.0,16.0,128.0,8.0,4300.0,213.0,2020,325,5.162097,5.519018
2,Honor,Android,16.69,yes,yes,13.0,8.0,128.0,8.0,4200.0,213.0,2020,162,5.111084,5.884631
3,Honor,Android,25.50,yes,yes,13.0,8.0,64.0,6.0,7250.0,480.0,2020,345,5.135387,5.630961
4,Honor,Android,15.32,yes,no,13.0,8.0,64.0,3.0,5000.0,185.0,2020,293,4.389995,4.947837

In [10]:
print("OLX")
olx.info()
print("\n" + "="*50)
print("eBay")
ebay.info()
print("\n" + "="*50)
print("Used Devices")
used.info()

OLX
<class 'pandas.DataFrame'>
RangeIndex: 3931 entries, 0 to 3930
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    3931 non-null   int64
 1   categoryName  3931 non-null   str
 2   userName      3931 non-null   str
 3   dateJoined    3931 non-null   str
 4   location      3912 non-null   str
 5   price         2758 non-null   str
 6   title         3930 non-null   str
 7   brand         2951 non-null   str
 8   condition     2109 non-null   str
 9   description   2979 non-null   str
 10  adId          3931 non-null   str
dtypes: int64(1), str(10)
memory usage: 337.9 KB

==================================================
eBay
<class 'pandas.DataFrame'>
RangeIndex: 17577 entries, 0 to 17576
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Uniq Id                17577 non-null  str
 1   Crawl Timestamp        17577 non-null  str
 2   Pageurl                17577 non-null  str
 3   Website                17577 non-null  str
 4   Title                  17565 non-null  str
 5   Num Of Reviews         0 non-null      float64
 6   Average Rating         0 non-null      float64
 7   Number Of Ratings      0 non-null      float64
 8   Model Num              1357 non-null   str
 9   Sku                    0 non-null      float64
 10  Upc                    3093 non-null   str
 11  Manufacturer           17576 non-null  str
 12  Model Name             17577 non-null  str
 13  Price                  17247 non-null  str
 14  Monthly Price          0 non-null      float64
 15  Stock                  17577 non-null  bool
 16  Carrier                1795 non-null   str
 17  Color Category         2819 non-null   str
 18  Internal Memory        2418 non-null   str
 19  Screen Size            1752 non-null   str
 20  Specifications         0 non-null      float64
 21  Five Star              3872 non-null   float64
 22  Four Star              3872 non-null   float64
 23  Three Star             3872 non-null   float64
 24  Two Star               3872 non-null   float64
 25  One Star               3872 non-null   float64
 26  Discontinued           17577 non-null  bool
 27  Broken Link            17577 non-null  bool
 28  Seller Rating          10988 non-null  str
 29  Seller Num Of Reviews  12280 non-null  str
dtypes: bool(3), float64(11), str(16)
memory usage: 3.7 MB

==================================================
Used Devices
<class 'pandas.DataFrame'>
RangeIndex: 3454 entries, 0 to 3453
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   brand_name             3454 non-null   str
 1   os                     3454 non-null   str
 2   screen_size            3454 non-null   float64
 3   4g                     3454 non-null   str
 4   5g                     3454 non-null   str
 5   main_camera_mp         3275 non-null   float64
 6   selfie_camera_mp       3452 non-null   float64
 7   int_memory             3450 non-null   float64
 8   ram                    3450 non-null   float64
 9   battery                3448 non-null   float64
 10  weight                 3447 non-null   float64
 11  release_year           3454 non-null   int64
 12  days_used              3454 non-null   int64
 13  normalized_used_price  3454 non-null   float64
 14  normalized_new_price   3454 non-null   float64
dtypes: float64(9), int64(2), str(4)
memory usage: 404.9 KB

In [11]:
print("OLX Missing Values")
print(olx.isnull().sum())
print("\n=========================\n")
print("eBay Missing Values")
print(ebay.isnull().sum())
print("\n=========================\n")
print("Used Devices Missing Values")
print(used.isnull().sum())

OLX Missing Values
Unnamed: 0         0
categoryName       0
userName           0
dateJoined         0
location          19
price           1173
title              1
brand            980
condition       1822
description      952
adId               0
dtype: int64

=========================

eBay Missing Values
Uniq Id                      0
Crawl Timestamp              0
Pageurl                      0
Website                      0
Title                       12
Num Of Reviews           17577
Average Rating           17577
Number Of Ratings        17577
Model Num                16220
Sku                      17577
Upc                      14484
Manufacturer                 1
Model Name                   0
Price                      330
Monthly Price            17577
Stock                        0
Carrier                  15782
Color Category           14758
Internal Memory          15159
Screen Size              15825
Specifications           17577
Five Star                13705
Four Star                13705
Three Star               13705
Two Star                 13705
One Star                 13705
Discontinued                 0
Broken Link                  0
Seller Rating             6589
Seller Num Of Reviews     5297
dtype: int64

=========================

Used Devices Missing Values
brand_name                 0
os                         0
screen_size                0
4g                         0
5g                         0
main_camera_mp           179
selfie_camera_mp           2
int_memory                 4
ram                        4
battery                    6
weight                     7
release_year               0
days_used                  0
normalized_used_price      0
normalized_new_price       0
dtype: int64

In [12]:
print("OLX")
print(olx.describe())
print("\n=========================\n")
print("Used Devices")
print(used.describe())

OLX
        Unnamed: 0
count  3931.000000
mean   1965.000000
std    1134.926282
min       0.000000
25%     982.500000
50%    1965.000000
75%    2947.500000
max    3930.000000

=========================

Used Devices
       screen_size  main_camera_mp  selfie_camera_mp   int_memory  \
count  3454.000000     3275.000000       3452.000000  3450.000000
mean     13.713115        9.460208          6.554229    54.573099
std       3.805280        4.815461          6.970372    84.972371
min       5.080000        0.080000          0.000000     0.010000
25%      12.700000        5.000000          2.000000    16.000000
50%      12.830000        8.000000          5.000000    32.000000
75%      15.340000       13.000000          8.000000    64.000000
max      30.710000       48.000000         32.000000  1024.000000

               ram      battery       weight  release_year    days_used  \
count  3450.000000  3448.000000  3447.000000   3454.000000  3454.000000
mean      4.036122  3133.402697   182.751871   2015.965258   674.869716
std       1.365105  1299.682844    88.413228      2.298455   248.580166
min       0.020000   500.000000    69.000000   2013.000000    91.000000
25%       4.000000  2100.000000   142.000000   2014.000000   533.500000
50%       4.000000  3000.000000   160.000000   2015.500000   690.500000
75%       4.000000  4000.000000   185.000000   2018.000000   868.750000
max      12.000000  9720.000000   855.000000   2020.000000  1094.000000

       normalized_used_price  normalized_new_price
count            3454.000000           3454.000000
mean                4.364712              5.233107
std                 0.588914              0.683637
min                 1.536867              2.901422
25%                 4.033931              4.790342
50%                 4.405133              5.245892
75%                 4.755700              5.673718
max                 6.619433              7.847841